spring:
  config:
    activate:
      on-profile: k8s

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:msa}
    username: ${POSTGRES_USER:msa}
    password: ${POSTGRES_PASSWORD:msa}

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8080}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://spring-security-authorization-server:9000/oauth2/jwks}

springmsa:
  internal-api:
    token: ${SPRING_MSA_INTERNAL_API_TOKEN}
