spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}

  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}

logging:
  level:
    org.hibernate.SQL: debug

springmsa:
  internal-api:
    token: ${SPRING_MSA_INTERNAL_API_TOKEN}
