server:
  port: 8081

spring:
  application:
    name: spring-user-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8080}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:9000/oauth2/jwks}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  charset:
    console: UTF-8
  level:
    com.springmsa.userservice: debug
    org.springframework.security: debug
