server:
  port: 8081

spring:
  application:
    name: spring-user-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  charset:
    console: UTF-8
  level:
    com.springmsa.userservice: debug
    org.springframework.security: debug

springmsa:
  internal-api:
    header-name: X-Internal-Token
